import MainLayout from "@/components/layout/MainLayout";
import { useState } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";

export default function IncrementalLift() {
  const [testConv, setTestConv] = useState("");
  const [controlConv, setControlConv] = useState("");

  const lift =
    parseFloat(testConv) > 0 && parseFloat(controlConv) >= 0
      ? (((parseFloat(testConv) - parseFloat(controlConv)) / parseFloat(controlConv)) * 100).toFixed(1)
      : null;

  return (
    <MainLayout>
      <div className="max-w-xl mx-auto px-6 py-12 space-y-8">
        <header className="text-center space-y-2">
          <h1 className="text-3xl font-bold">Incremental Lift Calculator</h1>
          <p className="text-muted-foreground text-lg">
            Estimate lift generated by your test campaign over a control.
          </p>
        </header>

        <Card>
          <CardHeader>
            <CardTitle>Enter Test and Control Group Results</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>Test Conversions</Label>
              <Input value={testConv} onChange={(e) => setTestConv(e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label>Control Conversions</Label>
              <Input value={controlConv} onChange={(e) => setControlConv(e.target.value)} />
            </div>
          </CardContent>
        </Card>

        {lift && (
          <div className="text-center mt-6">
            <p className="text-lg">
              Incremental Lift: <span className="font-semibold">{lift}%</span>
            </p>
          </div>
        )}
      </div>
    </MainLayout>
  );
}
